### ISSUE TITLE
video absolute path

### ISSUE THREAD

**Issue by anaschaudhary33** [alajovic/vicor#4]
Hey! I want to know that how to make this script work if I provide a full path of video file (not directory).
Full path can be given by tasker file picker

**Comment by alajovic** [comment]
Yeah, I think it would be easy to support such a mode. If I understand correctly, your use case is that you would call `vicor` from another application that would pass the video filename as the argument, right? Everything else proceeds as usual, i.e. the transcoded video is written to `vicor`'s default output directory, and you get a menu asking you for further actions (open, share, remove, quit).

**Comment by anaschaudhary33** [comment]
Yes, exactly what I want.
Please tell me how to do that

**Comment by alajovic** [comment]
Implemented. Please pull and test the latest version and let me know if it works as expected.

**Comment by anaschaudhary33** [comment]
Thanks. Working perfectly
